BEGIN;

DROP TABLE IF EXISTS PRICES;

CREATE EXTENSION IF NOT EXISTS BTREE_GIST;

CREATE TABLE PRICES (
    ID         BIGSERIAL PRIMARY KEY,
    START_DATE DATE,
    END_DATE   DATE,
    START_TIME TIME NOT NULL,
    END_TIME   TIME NOT NULL,
    PRICE      INT NOT NULL CHECK (PRICE > 0),

    CHECK (
        START_DATE IS NULL
        OR END_DATE   IS NULL
        OR START_DATE <= END_DATE
    ),
    CHECK (START_TIME < END_TIME)
);

COMMIT;
