name: Deploy Have Place API

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: mvn clean package -DskipTests

      - name: Copy JAR to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "target/*.jar"
          target: "havePlace/apps"
          strip_components: 1

      - name: Run Application via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd havePlace/apps
            
            sudo truncate -s 0 application.log || true
            
            sudo nohup java -jar *.jar >> application.log 2>&1 &
            
            exit 0

#      - name: Run deploy script via SSH
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            cd havePlace
#
#            git pull origin main
#
#            (sudo pkill -f "spring-boot:run") || true
#
#            sudo truncate -s 0 application.log
#
#            sudo nohup sudo mvn spring-boot:run >> application.log 2>&1 < /dev/null &
#
#            sleep 3